name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: hassevini
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=blue

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
